"""rename age to user_age

Revision ID: 58c7df676aed
Revises: 3efc074b8083
Create Date: 2026-09-17 11:17:14.927556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c7df676aed'
down_revision: Union[str, Sequence[str], None] = '3efc074b8083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_age', sa.Integer(), nullable=False))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), nullable=False))
    op.drop_column('users', 'user_age')
    # ### end Alembic commands ###
